Update python-app.yml (only push when dataset changes

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -35,5 +35,9 @@ jobs:
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
         git add .
-        git commit -m "Automated update: preprocess new dataset [skip ci]"
-        git push origin main
+        if ! git diff --cached --quiet; then
+          git commit -m "Automated update: preprocess new dataset [skip ci]"
+          git push origin main
+        else
+          echo "No changes to dataset. Aborting."
+        fi
